### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by JogicPogic** [lutraconsulting/qgis-geocat-plugin#1]
Hello.
I have PostGIS connection, calling in russian "Бузулукский бор".
I configure plugin as described on screenshot:
![1-settings](https://cloud.githubusercontent.com/assets/13277024/12070144/c6162690-b084-11e5-8c3c-c2ac4691596d.png)

I trying search for some text,
![2-search text](https://cloud.githubusercontent.com/assets/13277024/12070152/5b6d2fae-b085-11e5-9e7a-25b69236aa96.png)

but this error occurs:
```
Ошибка при выполнении сценария Python: 

TypeError: missing dsn and no parameters 
Traceback (most recent call last):
  File "C:/Users/Andrew/.qgis2/python/plugins\LayerMetadataSearch\geo_cat_dialog.py", line 94, in search
    cur = self._db_cur()
  File "C:/Users/Andrew/.qgis2/python/plugins\LayerMetadataSearch\geo_cat_dialog.py", line 72, in _db_cur
    con = get_connection(con_info)
  File "C:/Users/Andrew/.qgis2/python/plugins\LayerMetadataSearch\dbutils.py", line 32, in get_connection
    conn = psycopg2.connect(**conn_info)
  File "d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\psycopg2\__init__.py", line 159, in connect
    raise TypeError('missing dsn and no parameters')
TypeError: missing dsn and no parameters


Версия Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Версия: 2.12.1-Lyon Lyon, 16760fd 

Python Path:
C:/Users/Andrew/.qgis2/python/plugins\processing
d:/PROGRA~2/QGISLY~1/apps/qgis/./python
C:/Users/Andrew/.qgis2/python
C:/Users/Andrew/.qgis2/python/plugins
d:/PROGRA~2/QGISLY~1/apps/qgis/./python/plugins
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
d:\PROGRA~2\QGISLY~1\bin\python27.zip
d:\PROGRA~2\QGISLY~1\apps\Python27\DLLs
d:\PROGRA~2\QGISLY~1\apps\Python27\lib
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\plat-win
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\lib-tk
d:\PROGRA~2\QGISLY~1\bin
d:\PROGRA~2\QGISLY~1\apps\Python27
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\PIL
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\win32
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\win32\lib
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\Pythonwin
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
d:\PROGRA~2\QGISLY~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Andrew/.qgis2//python
d:\PROGRA~2\QGISLY~1\apps\qgis\python\plugins\fTools\tools
D:/Maps/PostGIS/Forestry
```

**Comment by mtravis** [comment]
I tested this on and also got that error. I then restarted QGIS and found that this resolved it.

We need to find a better solution for this but for now use just restart QGIS.
