### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-geocat-plugin#21]
Steps to reproduce:

Clear any custom config and restart QGIS
Do a search
Close search, add a new metadata column
Go to search again:

KeyError: u'uploader' 
Traceback (most recent call last):
  File "C:/Users/Pete/.qgis2/python/plugins\LayerMetadataSearch\geo_cat.py", line 190, in run
    self.dlg.display_details(cur_row)
  File "C:/Users/Pete/.qgis2/python/plugins\LayerMetadataSearch\geo_cat_dialog.py", line 256, in display_details
    val = self.search_results[current_row][col_name]
KeyError: u'uploader'

This seems OK after restarting QGIS

**Comment by erpas** [comment]
Done already.
