### ISSUE TITLE
Traceback after changing date column to text field

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-geocat-plugin#23]
Steps:

1. Clear config and restart QGIS
2. Add a text field with date string as a QDate widget
3. Try to do a search:

KeyError: u'text_date' 
Traceback (most recent call last):
  File "C:/Users/Pete/.qgis2/python/plugins\LayerMetadataSearch\geo_cat.py", line 190, in run
    self.dlg.display_details(cur_row)
  File "C:/Users/Pete/.qgis2/python/plugins\LayerMetadataSearch\geo_cat_dialog.py", line 256, in display_details
    val = self.search_results[current_row][col_name]
KeyError: u'text_date'

Check should be made in config that QDate is associated with a 'date' type in Postgres

**Comment by erpas** [comment]
Done check for QDateEdit - Postgres columns can be of type:

* date
* timestamp
